<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml"); ?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
			<!-- CONTENT -->
			<section class="customform">
				<h1>Administration Tools</h1>
				<div> <button class='s-2' onClick="window.location.href='checkReports.php'"><b> Check Reports </b></button> 
				<button class='s-2' onClick="window.location.href='deleteTopics.php'"><b> Delete Topics </b></button> 
				<button class='s-2' onClick="window.location.href='manageUser.php'"><b> Manage Users </b></button> </div>
			</section>
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>