<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml"); ?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
			<!-- CONTENT -->
			<section class="s-12 l-12 ">
				<h1>Threads</h1>
				<div class="margin">
					<table class="responstable">
						<tr>
							<th>Report ID</th>
							<th>Object Type</th>
							<th>Reporting Users ID</th>
							<th>Date</th></tr>
							 <?php foreach ( $this->reports as $report ) :?> 
							 <tr onClick="window.location.href='manageReport.php?r_id=<?php echo($report['Report_id'])?>'" style="cursor: pointer;">
								<td><a> <?php echo $report['Report_id'];?> 
								</a></td>
								<?php if ($report['Post_id'] != 0) :?>								
									<td> Post </td>
								<?php else : ?>					
									<td> Thread </td>						
								<?php endif ?>
								<td> <?php echo $report['User_id']; ?></td>
								<td> <?php echo $report['Date']; ?> 
								</td>
							</tr>
	 						 <?php endforeach ?>
					</table>

				</div>
			</section>
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>