<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml");?>

<div class="line">
	<div class="box margin-bottom">
		<div class="margin">
			<article class="customform s-6 l-8">
				<h1>Change Password</h1>
				<form action="PasswordEdit.php" method="post">
					<div class="PasswordError"><?php if (isset($error['message'])) {echo $error['message'];} ?></div>


					<div>
						<span class="PasswordError"><?php if (isset($error['icon'])) {echo $error['icon'];} ?></span>
						New Password<span class="signupError"><?php if (isset($error['password'])) {echo $error['password'];} ?></span>
						<input type="password" name="password" value="" />
					</div>

					<div>
						Confirm Password<span class="PasswordError"><?php if (isset($error['confirm'])) {echo $error['confirm'];} ?></span>
						<input type="password" name="confirm_password" value="" />
					</div>
					<button type="submit" class="s-3" style="margin-right: 30px">Change</button>
					<button type="button" class="s-3" onClick="window.location.href='<?php echo$_SESSION ['previous_page']; ?>'"><b>Cancel</b></button>
					<br />
				</form>
			</article>
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>