<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml"); ?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
		<!--  
			<!-- CONTENT -->
			<section class="s-12 l-9 right">
				<h1>Threads</h1>
				<div class="margin">
					<table class="responstable">
						<tr>
							<th>Name</th>
							<th>Number of posts</th>
							<th>Views</th>
							<th>Date of creation</th>
							<th>Owner</th>
							<th>Options</th>
							<td><a href="thread.php?id=<?php echo($this->report['Thread_id'])?>">
									<?php echo $this->report['Name'];?>
									<?php if ($this->report['thread_status'] == 1) :?> <warning> (Locked) </warning>
									<?php endif ?>
							 </a></td>
							<td> <?php echo $this->report['Post_count']; ?></td>
							<td> <?php echo $this->report['Views']; ?> </td>
							<td> <?php echo $this->report['Date']; ?> </td>
							<td> <?php echo $this->report['Username']; ?> </td>
							<td><a href="delete.php?t_id=<?php echo($this->report['Thread_id'])?>">Delete</a><br>
							<?php if ($row['thread_status'] == 1) :?>
								<a href="toggleLock.php?t_id=<?php echo($this->report['Thread_id'])?>">Unlock</a> <br>
							<?php else :?>
								<a href="toggleLock.php?t_id=<?php echo($this->report['Thread_id'])?>">Lock</a> <br>
							<?php endif?>
							<a href="renameThread.php?t_id=<?php echo($this->report['Thread_id'])?>">Rename</a></td> 
							</tr>
					</table>
					<!--New thread button-->
					<form class="customform">
						<button  type="button" class="customform s-9 l-2" onClick="window.location.href='newThread.php?top_id=<?php echo($this->topic)?>'"><b>New thread</b></button>
					</form>
				</div>
			<br>
			</section>-->			
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>