<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>User Management</title>
</head>
<body>

<?php include ("header.phtml");?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
			<!-- CONTENT -->
			<section class="s-12">
				<h1>Users</h1>
				<div class="margin">
					<table class="responstable">
						<tr>
							<th>Username</th>
							<th>User ID</th>
							<th>Email</th>
							<th>Status</th>
							<th>Type</th>
							</tr> <?php foreach ( $this->users as $user ) :?> 
							<tr onClick="window.location.href='manageUser.php?u_id=<?php echo($user['User_id'])?>'" style="cursor: pointer;">
								<td><?php echo($user['Username'])?></td>
								<td><?php echo($user['User_id'])?></td>
								<td><?php echo $user['Email']; ?></td>
								<?php if ($user['Status'] != 0) :?>
									<td>Banned</td>
								<?php else :?>
									<td>In good standing</td>
								<?php endif?>
								<?php if ($user['Priviledge'] == 2) :?>
									<td>Administrator</td>
								<?php elseif ($user['Priviledge'] == 1) :?>
									<td>Moderator</td>
								<?php else:?>
									<td>General</td>
								<?php endif?>
								</tr>
	 						 <?php  endforeach?>
					</table>
				</div>
			<br>
			</section>
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>