<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>New Topic</title>
</head>
<body>

<?php include ("header.phtml");?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
			<!-- CONTENT -->
			<section class="s-12 l-9 right">
				<h1>New Topic</h1>
				<div class="margin">

					<!--Add new thread-->
					<form action="newtopic.php?top_id=<?php echo($_GET['top_id']);?>" method="post"
						class="customform s-12">
						<div>
							Topic Name: <input type="text" name="topic_name">
						</div>

						<div class="s-2">
							<button type="submit">Create</button>
						</div>
					</form>

				</div>
			</section>
						
			<!-- ASIDE NAV -->
			<?php include("navigation.phtml")?>
		</div>
	</div>
</div>

<?php include("footer.phtml")?>