<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml");?>

<div class="line">
	<div class="box margin-bottom">
		<div class="margin">
			<!-- CONTENT -->
			<article class="customform s-12 l-8">
				<h1>Personal Settings</h1>
       			<?php echo "Name: " . $_SESSION ['user'] ['First_name'] . " " . $_SESSION ['user'] ['Last_name'];	?><br />
				<?php echo "Username: " . $_SESSION ['user'] ['Username']; ?><br />
				<?php echo "Post count: " . $_SESSION ['user'] ['Post_count']; ?><br />
				<?php echo "Account Type: "?>
				<?php if ($_SESSION ['user']['Priviledge'] == 0) :?>
					<?php echo "General" ?><br />
				<?php elseif ($_SESSION ['user']['Priviledge'] == 1) :?>
					<?php echo "Moderator" ?><br />
				<?php else :?>
					<?php echo "Administrator" ?><br />
				<?php endif?>
				<?php echo "Email: " . htmlentities ( $_SESSION ['user'] ['Email'], ENT_QUOTES, 'UTF-8' ) . ""; ?><br />
				<button type="button" class="s-3" onClick="window.location.href='editName.php'"	style="margin-right: 30px"><b>Change Name</b></button>
				<button type="button" class="s-3" onClick="window.location.href='editPassword.php'"><b>Change Password</b></button>
				<br /> <br />
			</article>
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>