<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Forum</title>
</head>
<body>

<?php include ("header.phtml"); ?>

<!-- ASIDE NAV AND CONTENT -->
<div class="line">
	<div class="box">
		<div class="margin">
			<!-- CONTENT -->
			<section class="s-12 l-9 right">
				<h1>Threads</h1>
				<div class="margin">
					<table class="responstable">
						<tr>
							<th>Name</th>
							<th>Number of posts</th>
							<th>Views</th>
							</tr> <?php foreach ( $this->rows as $row ) :?> <tr>
								<td><a
									href="posts.php?id=<?php echo($row['Thread_id'])?>&obj=<?php echo($row['Object_id'])?>&views=<?php echo($row['Views'])?>&posts=<?php echo($row['Post_count'])?>">
										<?php if ($row['thread_status'] == 1) :?>
											<?php echo $row['Name']." <font color=\"red\">(Locked)</font>";?>
										<?php else :?>
											<?php echo $row['Name'];?>
										<?php endif?>  
								 </a></td>
								<td> <?php echo $row['Post_count']; ?></td>
								<td> <?php echo $row['Views']; ?> </td>
								</tr>
	 						 <?php  endforeach ?>
					</table>
					<!--New thread button-->
					<form class="customform">
						<button  type="button" class="customform s-9 l-2" onClick="window.location.href='newthread.php'"><b>New thread</b></button>
					</form>
				</div>
			<br>
			</section>
			
			<?php include ("navigation.phtml")?>
			
		</div>
	</div>
</div>

<!-- FOOTER -->
<?php include ("footer.phtml"); ?>

</body>
</html>